version: "3.9"


x-environment-defaults: &environment-defaults
  DATABASE_URL: "postgresql://django:django@db:5432/django"
  DEBUG: 1

services:
  django:
    restart: always
    build: ./backend
    command: sh -c "gunicorn --bind 0.0.0.0:8000 wtasker.wsgi:application --workers 10"
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
      - static_data:/backend/static
    depends_on:
      - db
    expose:
      - 80
    environment:
       <<: *environment-defaults
  
  frontend:
    restart: always
    build: ./frontend/wtasker
    expose:
      - 3000

  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "81:80"
    volumes:
      - static_data:/var/www/html/static/
      - ./nginx:/etc/nginx/conf.d

volumes:
  pg_data:
  static_data:
  redis_data: